# Setup
title: myBlog
tagline: A responsive theme for your project on GitHub Pages
baseurl: ""
paginate: 1

# About/contact
author: ppoasdd
name: ppoasdd
url: https://ppoasdd.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
