# Setup
title: ppoasdd's Blog
tagline: Record my thoughts
baseurl: ""
paginate: 1

# About/contact
author: ppoasdd
name: ppoasdd
url: https://ppoasdd.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
    
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
